version: '3'

services:
  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./vol_certs:/etc/certs:ro
      - ./vol_conf:/conf:ro
      - ./traefik.yml:/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    labels:
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`${VIRTUAL_HOSTNAME}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=80
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.usersfile=/conf/users
    networks:
      MyNetwork:

networks:
  MyNetwork:
    external: true

