global:
  sendAnonymousUsage: false
  checkNewVersion: false

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: :443

api: {}

pilot:
  dashboard: false

log:
  level: ERROR

# accessLog: {}

providers:
  docker:
    watch: true
    network: MyNetwork
  file:
    directory: /conf
    watch: true
  providersThrottleDuration: 10
