tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/cert.crt
        keyFile: /etc/certs/cert.key
  certificates:
     certFile: /etc/certs/cert.crt
     keyFile: /etc/certs/cert.key
